### ISSUE TITLE
deepl使用受到翻译次数限制了

### ISSUE THREAD

**Issue by ACommoners** [infrost/DeeplxFile#11]
![1](https://github.com/user-attachments/assets/5472005a-7f0e-435b-a8a0-f6f52a9b7950)

**Comment by infrost** [comment]
请从以下解决方案中选择一种：

1. 【playwright设置】里勾选【edge浏览器不使用用户数据】。
![image](https://github.com/user-attachments/assets/657c13c2-7a7a-463d-a235-257da0519f82)
2.  使用完整版的软件，【playwrigh设置】取消勾选【使用系统edge浏览器】，这样会调用webkit浏览器。
3.  关闭/切换到其他代理服务器
