### ISSUE TITLE
翻译结果中存在大量的[...]

### ISSUE THREAD

**Issue by Rocky-94** [infrost/DeeplxFile#12]
hi 大佬
在使用最新的 0.5.9版本时，在翻译文档文件时，生成的结果文档中会有大量的[...] 输出

比对了下原文件和结果文件，文字更多的表格可能容易出现这个问题，但是没有规律

![image](https://github.com/user-attachments/assets/c1c01df3-141c-4c84-a211-e114353a4546)
![image](https://github.com/user-attachments/assets/09f9544f-d724-4179-ae70-c04089d1c554)

上面两个图是结果文档与原文档的对照

旧版本会出现行数不必对的循环，但是强制输出的部分无此内容

**Comment by infrost** [comment]
我的问题，这个是因为修改了行数匹配逻辑引出的bug。
原因是deepl如果内容没有翻译完会用`[...]`代替，程序在deepl没有翻译完的时候就尝试获取内容，然后写入了。
我会尽快修复该问题。

**Comment by infrost** [comment]
临时的解决方法是，多翻译几次 会有正常的😂😂😂😂

**Comment by infrost** [comment]
已解决，感谢反馈，如有其他问题欢迎新开issue。
