### ISSUE TITLE
0.5.10版本翻译有同#12 相同的[...]问题

### ISSUE THREAD

**Issue by Rocky-94** [infrost/DeeplxFile#14]
hi，大佬~

使用V0.5.10 版本依然会有 #12 的问题，现象基本相同
多次对比，勾选强制指定语言会有所改善，但是依然有大量未翻译出的[...] 出现在结果行中

**Comment by infrost** [comment]
正在定位问题
您试试使用文档恢复功能，选择上一次翻译出现了[...]的文档进行恢复，文档是否恢复正常？
**注意是选择原始文档**

> 例如：翻译原始文件：abc.docx, 翻译后文件： abc_translated.docx, 选择`abc.docx`

![image](https://github.com/user-attachments/assets/5a6a17ff-a5ee-43b2-9a1c-452a721a5ee6)

**Comment by infrost** [comment]
找到问题了，稍后更新 这次应该是真没问题了😂

**Comment by infrost** [comment]
麻烦您试一下[release](https://github.com/infrost/DeeplxFile/releases/tag/V0.5.10)里`deeplxfile_v0.5.10patch.zip`这个版本，还有问题吗？

**Comment by Rocky-94** [comment]
> 麻烦您试一下[release](https://github.com/infrost/DeeplxFile/releases/tag/V0.5.10)里`deeplxfile_v0.5.10patch.zip`这个版本，还有问题吗？

谢谢大佬，我去下一下试试~ 不太清楚为啥这个压缩包下载超级慢，需要等下好后才能反馈

**Comment by infrost** [comment]
> > 麻烦您试一下[release](https://github.com/infrost/DeeplxFile/releases/tag/V0.5.10)里`deeplxfile_v0.5.10patch.zip`这个版本，还有问题吗？
> 
> 谢谢大佬，我去下一下试试~ 不太清楚为啥这个压缩包下载超级慢，需要等下好后才能反馈

http://i.2.996h.cn/#s/-w7EGpdg
网盘下可能会快一些

**Comment by Rocky-94** [comment]
> 麻烦您试一下[release](https://github.com/infrost/DeeplxFile/releases/tag/V0.5.10)里`deeplxfile_v0.5.10patch.zip`这个版本，还有问题吗？

使用这个patch版本试了下没有问题了，[...]问题再现了~
感谢大佬~~
