### ISSUE TITLE
关于对PDF文档的翻译支持

### ISSUE THREAD

**Issue by LYZ10** [infrost/DeeplxFile#2]
您好呀，请问什么时候会支持PDF翻译呢？再次感谢您开发这么好的工具！

**Comment by infrost** [comment]
您好，感谢您的关注和对项目的支持。
关于对PDF文档的支持已在开发日程上了，不过PDF文档的解析会比较复杂 需要点时间。

**Comment by LYZ10** [comment]
明白的！辛苦啦，请加油加油。

**Comment by infrost** [comment]
![image](https://github.com/user-attachments/assets/46ce7a0e-9d54-4e55-a883-3c265b16bee6)
![2024-08-31_01-26-05](https://github.com/user-attachments/assets/80dc6891-42f4-4dc3-a7c7-66c19d1ba46c)

目前测试中的程序已经能做到**将PDF文件尽量保留格式的同时将其翻译为可编辑形式的word(.docx)文档**，这原本是DeepL官方订阅版服务才能做到的功能。

但是需要说明的是：
- PDF的解析和对应word文档生成方法源自于[ArtifexSoftware的项目](https://github.com/ArtifexSoftware)，专业的人做专业的事，就不重复造轮子了。

- 我并不会直接把这个`把PDF保留原格式翻译成Word`的功能直接集成在该项目中，而是会新开一个repository，提供一个封装好可以直接供`deeplxfile`调用进行翻译PDF接口的`pdf2word`程序，相当于把PDF的翻译功能插件化。

- 原因是由于PDF种类多样，他的解析是相当复杂的，而PDF文档的生成更为复杂，（我猜这也是著名纯python项目pypdf不支持生成PDF的原因之一吧）。PDF文件包含了大量的元数据、字体嵌入、图像压缩、加密等，确保在不同的环境下仍然可以正确显示甚至与之交互。这种跨平台的要求使得PDF的内部结构比普通文档格式复杂得多。

  - 哪怕是[`DeepL官方`的PDF翻译方法](https://support.deepl.com/hc/en-us/articles/4411308018450-Translation-of-PDF-files)，都是依赖光学字符识别的，做不到100%保留原格式或者没有识别错误。
  - 对PDF文档的OCR，一定要用到OpenCV这个大型库（库本身就几百MB），这个在软件分发的过程中是相当不利的。封装好的PDF模块解压后超过`500MB`。我不太能接受一个PDF文档解析的功能比我软件的其他实现还大得多，它更适合成为一个单独的应用程序。
  - 解析/重新生成的文档版式出现一些不对是正常的，因为其实这里面有相当的内容甚至涉及到了机器学习以及NLP方面的东西，这个很难完美，基本上是各个pdf库的长期目标了。
