### ISSUE TITLE
废了，deepl增加了真人验证，直接就失败

### ISSUE THREAD

**Issue by martjay** [infrost/DeeplxFile#4]
还不如弄deeplx接口直接翻译呢，有推荐的支持deeplx翻译文档的软件吗

**Comment by infrost** [comment]
1. 如果翻译失败请提供具体日志供查看，否则无法定位问题。
2. **软件默认调用的就是deeplx的接口**，如果是deeplx返回的503值，那么我无能为力，这是deeplx的问题。
3. 自行实现的playwright模式理论上是比deeplx更稳定的。新版本提供了一个登录暂停选项，打开deepl网页后会暂停运行登录后再进行翻译。
4. 这个就是支持deeplx翻译的软件，如果已现有同类软件那我不会做这个项目。
5. 如果playwright模式出现真人验证（我并没有遇到过这种情况）或者显示翻译达到限额等错误，deeplx更不可能能成功翻译。请检查是否是使用了梯子代理了Deepl流量，Deepl会针对ip进行封禁。如果ip被ban了只能换ip。
