### ISSUE TITLE
无法进行超长文本翻译

### ISSUE THREAD

**Issue by bwy727** [infrost/DeeplxFile#7]
开始翻译后，弹出了edge浏览器的deepl网页，可翻译没多久提示已经达到限额。请问如何突破这个限制实现长文本翻译？

**Comment by infrost** [comment]
> 开始翻译后，弹出了edge浏览器的deepl网页，可翻译没多久提示已经达到限额。请问如何突破这个限制实现长文本翻译？

这个是项目的长期目标。
已知如果是用edge进行翻译的话，其实开启`edge浏览器不使用用户数据` 有时候还会比在一个使用了免费用户登录的正常edge窗口里能进行更多的翻译。目前来说，**如果很长很长的文档，您可以尝试`不使用用户数据`，或者用完整版里的Webkit内核的调用，然后把文档拆分丢给软件（因为有时候单次达到最大限额后，重启浏览器又能翻译了）**，后续会实现自动重启浏览器尝试。

本质上，本项目绕过deepl官方限制进行文档翻译的方法，又或者是调用的`deeplx`这个项目的方法都属于所谓的`奇技淫巧`，我们只能在deepl的`硬限制`之下做尽可能多的努力。`Deepl`本身会有一些硬限制如：针对ip地址的每日最大翻译量限制（这种限制几乎无法绕开）等，如果想实现非常稳定的超长文本翻译，且有条件的话，我建议用支持国际支付的信用卡验证deepl，申请一个免费版的deepl api，每个月有500,000的字符额度。如果有调用官方api需求，我会在项目里开放这个功能，这不难实现。

**Comment by 2h0000** [comment]
> > 开始翻译后，弹出了edge浏览器的deepl网页，可翻译没多久提示已经达到限额。请问如何突破这个限制实现长文本翻译？
> 
> 这个是项目的长期目标。 已知如果是用edge进行翻译的话，其实开启`edge浏览器不使用用户数据` 有时候还会比在一个使用了免费用户登录的正常edge窗口里能进行更多的翻译。目前来说，**如果很长很长的文档，您可以尝试`不使用用户数据`，或者用完整版里的Webkit内核的调用，然后把文档拆分丢给软件（因为有时候单次达到最大限额后，重启浏览器又能翻译了）**，后续会实现自动重启浏览器尝试。
> 
> 本质上，本项目绕过deepl官方限制进行文档翻译的方法，又或者是调用的`deeplx`这个项目的方法都属于所谓的`奇技淫巧`，我们只能在deepl的`硬限制`之下做尽可能多的努力。`Deepl`本身会有一些硬限制如：针对ip地址的每日最大翻译量限制（这种限制几乎无法绕开）等，如果想实现非常稳定的超长文本翻译，且有条件的话，我建议用支持国际支付的信用卡验证deepl，申请一个免费版的deepl api，每个月有500,000的字符额度。如果有调用官方api需求，我会在项目里开放这个功能，这不难实现。

作者，你好，感谢你的软件。
我也遇到了同样的问题，用edge浏览器打开deepl网页，没多久提示限额。我想问的是如何得到已经翻译好的部分内容，限额后软件一直卡在写入翻译结果，而源文件还是翻译前的语言，已经翻译好的部分我在哪能找到呢，还是说软件一直卡在那，就得不到已经翻译好的部分，如何手动的保存已经翻译好的呢。

**Comment by infrost** [comment]
> > > 开始翻译后，弹出了edge浏览器的deepl网页，可翻译没多久提示已经达到限额。请问如何突破这个限制实现长文本翻译？
> > 
> > 
> > 这个是项目的长期目标。 已知如果是用edge进行翻译的话，其实开启`edge浏览器不使用用户数据` 有时候还会比在一个使用了免费用户登录的正常edge窗口里能进行更多的翻译。目前来说，**如果很长很长的文档，您可以尝试`不使用用户数据`，或者用完整版里的Webkit内核的调用，然后把文档拆分丢给软件（因为有时候单次达到最大限额后，重启浏览器又能翻译了）**，后续会实现自动重启浏览器尝试。
> > 本质上，本项目绕过deepl官方限制进行文档翻译的方法，又或者是调用的`deeplx`这个项目的方法都属于所谓的`奇技淫巧`，我们只能在deepl的`硬限制`之下做尽可能多的努力。`Deepl`本身会有一些硬限制如：针对ip地址的每日最大翻译量限制（这种限制几乎无法绕开）等，如果想实现非常稳定的超长文本翻译，且有条件的话，我建议用支持国际支付的信用卡验证deepl，申请一个免费版的deepl api，每个月有500,000的字符额度。如果有调用官方api需求，我会在项目里开放这个功能，这不难实现。
> 
> 作者，你好，感谢你的软件。 我也遇到了同样的问题，用edge浏览器打开deepl网页，没多久提示限额。我想问的是如何得到已经翻译好的部分内容，限额后软件一直卡在写入翻译结果，而源文件还是翻译前的语言，已经翻译好的部分我在哪能找到呢，还是说软件一直卡在那，就得不到已经翻译好的部分，如何手动的保存已经翻译好的呢。

您好，软件运行目录`\out`文件夹下会有一个`translated_result.txt`的原始翻译文件，您可以尝试查看一下。
感谢提出该issue，我之后会添加一个终止翻译的功能，强制让已翻译完成的部分写入文档，目前浏览器模式对于出错的处理逻辑确实是不够充分的。

**Comment by infrost** [comment]
[V0.5.7](https://github.com/infrost/DeeplxFile/releases/tag/V0.5.7)的release已尝试解决该问题
